### ISSUE TITLE
Not needed so could be deleted

### ISSUE THREAD

**Issue by dbackeus** [daveio/dnsimple-export#2]
DNSimple now supports exporting to BIND text from within the UI: https://support.dnsimple.com/articles/zone-files/#exporting-records-to-a-zone-file

Might be worth deleting this repo or adding a DEPRECATED notice at top of README or something. I somehow got this repo before the dnsimple documentation when googling so wasted a bit of time.

**Comment by daveio** [comment]
Thanks for filing this, I'll add a notice of deprecation. I want to keep it online as it might be useful as a building block for other custom exports, but you're right that users should use the native functionality now it's present.
